# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 04:12
from __future__ import unicode_literals
from django.db import migrations, models
from movie_data.models import Movie, Review
from django.db.models import Count


def get_count(apps, schema_editor):

    for movie in Movie.objects.values():
        movie_obj = Movie.objects.get(id=movie['id'])
        count = Review.objects.filter(movie_id=movie['id']).aggregate(Count('rating'))
        movie_obj.num_reviews = count['rating__count']
        movie_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movie_data', '0004_auto_20160509_0353'),
    ]

    operations = [

        migrations.RunPython(get_count)
    ]
