# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 20:17
from __future__ import unicode_literals
import csv

from django.db import migrations
from django.contrib.auth.models import User
from movie_data.models import Critic
from django.contrib.auth.models import User

male_list = []
female_list = []


def process_rand_users():
    rand_names = '/Users/Nic/TIY/W6/movielens/movielens/auth_user/data/ran_names.csv'
    fieldnames = ['first','last','sex','username','email']

    with open(rand_names) as f:
        reader = csv.DictReader(f, fieldnames=fieldnames, delimiter=',')

        for user_info in reader:
            if user_info['sex'] == 'M':
                male_list.append(user_info)
            else:
                female_list.append(user_info)


def create_account(apps, schema):
    process_rand_users()

    for i, critic in enumerate(Critic):
        if critic.sex == 'M':
            user = User.objects.create_user(
                male_list[i]['username'],
                male_list[i]['email'],
                male_list[i]['password'],
            )
            user.first_name = male_list[i]['first']
            user.last_name = male_list[i]['last']
        else:
            if critic.sex == 'F':
                user = User.objects.create_user(
                    female_list[i]['username'],
                    female_list[i]['email'],
                    female_list[i]['password'],
                )
                user.first_name = female_list[i]['first']
                user.last_name = female_list[i]['last']


def delete_item(user_dict):
    pass


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        # migrations.RunPython()
    ]


# CSV WORKS. CONVERT CSV DATA TO USERS
# CREATE LOGIN PAGE AND WHAT NOT