# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 20:17
from __future__ import unicode_literals
import csv

from django.db import migrations
from movie_data.models import Critic
from django.contrib.auth.models import User


master_list = []


def process_rand_users():
    rand_names = '/Users/Nic/TIY/W6/movielens/movielens/auth_user/data/ran_names.csv'
    fieldnames = ['first','last','sex','username','email']

    with open(rand_names) as f:
        reader = csv.DictReader(f, fieldnames=fieldnames, delimiter=',')

        for user_info in reader:
            master_list.append(user_info)


def create_account(apps, schema):
    process_rand_users()
    x = 2
    for i, critic in enumerate(Critic.objects.all()):
        user, was_created = User.objects.get_or_create(
            id = x,
            username = master_list[i]['username'],
            password ='password',
            email = master_list[i]['email'],
            first_name = master_list[i]['first'],
            last_name = master_list[i]['last'],
        )
        x += 1


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_account)
    ]


# CSV WORKS. CONVERT CSV DATA TO USERS
# CREATE LOGIN PAGE AND WHAT NOT