# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_data', '0005_auto_20160509_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.TextField(default=''),
        ),
    ]
