# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_data', '0006_movie_imdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdb',
            new_name='imdb_link',
        ),
        migrations.AddField(
            model_name='movie',
            name='g_action',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_adventure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_animation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_comedy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_crime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_documentary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_drama',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_fantasy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_horror',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_musical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_noir',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_romance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_scifi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_thriller',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_unknown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_war',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='g_western',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.TextField(default=''),
        ),
    ]
