# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 03:51
from __future__ import unicode_literals
from django.db import migrations, models
from movie_data.models import Movie, Review
from django.db.models import Avg


def get_avg_rating_movie(apps, schema_editor):

    for movie in Movie.objects.values():
        movie_obj = Movie.objects.get(id=movie['id'])
        print("movie obj = ", movie_obj)
        avg = Review.objects.filter(movie_id=movie['id']).aggregate(Avg('rating'))
        print("avg = ", avg)
        movie_obj.avg_rating = (avg['rating__avg'])
        print("SAVING")
        movie_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movie_data', '0002_movie_avg_rating'),
    ]

    operations = [
        migrations.RunPython(get_avg_rating_movie)
    ]
