# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_data', '0003_auto_20160509_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
